name: partnext
description: "Partnext mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl:

  # Core
  get_it: 8.0.0
  provider: 6.1.2
  go_router: 14.3.0

  # Storage
  shared_preferences: 2.3.2
  flutter_secure_storage: 9.2.2

  # Network
  http: 1.2.2
  mime: 1.0.5

  # Utils
  logger: 2.4.0
  path_provider:
  path:

  # UI
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.10+1

  # Code generation
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: 5.0.0
  dart_code_metrics_presets: 2.17.0

  # Code generation
  build_runner:
  flutter_gen_runner:
  json_serializable:

flutter:
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/app/assets/
  integrations:
    flutter_svg: true
