import 'package:partnext/app/l10n/l10n.dart';

enum InterestType {
  artAndEntertainment,
  music,
  banking,
  finance,
  consulting,
  creatives,
  fashion,
  mediaAndJournalism,
  sales,
  governmentAndPolitics,
  vCAndInvestment,
  education,
  medicine,
  marketing,
  publicRelations,
  tech,
  advertising,
  insurance,
  realEstate,
  lawPolicy,
  travelHospitality,
  policeMilitary,
  constructions,
  manufacturing,
  foodAndBeverage,
  counseling,
  other;

  const InterestType();

  @override
  String toString() => switch (this) {
        InterestType.artAndEntertainment => l10n?.art_and_entertainment ?? '',
        InterestType.music => l10n?.music ?? '',
        InterestType.banking => l10n?.banking ?? '',
        InterestType.finance => l10n?.finance ?? '',
        InterestType.consulting => l10n?.consulting ?? '',
        InterestType.creatives => l10n?.creatives ?? '',
        InterestType.fashion => l10n?.fashion ?? '',
        InterestType.mediaAndJournalism => l10n?.media_and_journalism ?? '',
        InterestType.sales => l10n?.sales ?? '',
        InterestType.governmentAndPolitics => l10n?.government_and_politics ?? '',
        InterestType.vCAndInvestment => l10n?.vc_and_investment ?? '',
        InterestType.education => l10n?.education ?? '',
        InterestType.medicine => l10n?.medicine ?? '',
        InterestType.marketing => l10n?.marketing ?? '',
        InterestType.publicRelations => l10n?.public_relations ?? '',
        InterestType.tech => l10n?.tech ?? '',
        InterestType.advertising => l10n?.advertising ?? '',
        InterestType.insurance => l10n?.insurance ?? '',
        InterestType.realEstate => l10n?.real_estate ?? '',
        InterestType.lawPolicy => l10n?.law_and_policy ?? '',
        InterestType.travelHospitality => l10n?.travel_and_hospitality ?? '',
        InterestType.policeMilitary => l10n?.police_and_military ?? '',
        InterestType.constructions => l10n?.constructions ?? '',
        InterestType.manufacturing => l10n?.manufacturing ?? '',
        InterestType.foodAndBeverage => l10n?.food_and_beverage ?? '',
        InterestType.counseling => l10n?.counseling ?? '',
        InterestType.other => l10n?.plus_other ?? '',
      };
}
